In [1]:
print ("deba")

deba


In [2]:
dir (print)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [4]:
help (self)

NameError: name 'self' is not defined

In [6]:
myset = {1,2,3}

In [7]:
myset

{1, 2, 3}

In [9]:
for i in myset:
    print (i)

1
2
3


In [10]:
myset.add(34)

In [11]:
myset

{1, 2, 3, 34}

In [12]:
myset.clear()

In [13]:
myset

set()

In [14]:
myset = {1,2,3,4}

In [15]:
myset

{1, 2, 3, 4}

In [17]:
myset.update([1,2,35,78])

In [18]:
myset

{1, 2, 3, 4, 35, 78}

In [19]:
myset.pop()

1

In [20]:
dir(myset)

['__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update']

In [21]:
help (myset)

Help on set object:

class set(object)
 |  set() -> new empty set object
 |  set(iterable) -> new set object
 |  
 |  Build an unordered collection of unique elements.
 |  
 |  Methods defined here:
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iand__(self, value, /)
 |      Return self&=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __ior__(self, value, /)
 |      Return self|=value.
 |  
 |  __isub__(self, value, /)
 |      Return self-=value.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __ixor__(self, value, /)
 |      Return self^=value.


In [22]:
myset.remove(1)

KeyError: 1

In [23]:
myset

{2, 3, 4, 35, 78}

In [25]:
myset.remove(2)

In [26]:
myset

{3, 4, 35, 78}

In [27]:
mydict = {'a':12,'b':34}

In [28]:
mydict

{'a': 12, 'b': 34}

In [29]:
mydict['f']=23

In [30]:
mydict

{'a': 12, 'b': 34, 'f': 23}

In [31]:
mydict["r"]=44

In [32]:
mydict

{'a': 12, 'b': 34, 'f': 23, 'r': 44}

In [33]:
d2 = {'dd':23 , 'ff':55}

In [34]:
mydict[d2]

TypeError: unhashable type: 'dict'

In [36]:
mydict['dd']=d2

In [37]:
mydict

{'a': 12, 'b': 34, 'f': 23, 'r': 44, 'dd': {'dd': 23, 'ff': 55}}

In [46]:
mydict = {"this is":"first line","this is":"second line","this is":"third line"}

In [47]:
mydict

{'this is': 'third line'}

In [48]:
mylist =  [

  {

    "name": "Meowsy",

    "species" : "cat",

    "foods": {

      "likes": ["tuna", "catnip"],

      "dislikes": ["ham", "zucchini"]

    }

  },

  {

    "name": "Barky",

    "species" : "dog",

    "foods": {

      "likes": ["bones", "carrots"],

      "dislikes": ["tuna"]

    }

  },

  {

    "name": "Purrpaws",

    "species" : "cat",

    "foods": {

      "likes": ["mice"],

      "dislikes": ["cookies"]

    }

  }

]

In [49]:
mylist

[{'name': 'Meowsy',
  'species': 'cat',
  'foods': {'likes': ['tuna', 'catnip'], 'dislikes': ['ham', 'zucchini']}},
 {'name': 'Barky',
  'species': 'dog',
  'foods': {'likes': ['bones', 'carrots'], 'dislikes': ['tuna']}},
 {'name': 'Purrpaws',
  'species': 'cat',
  'foods': {'likes': ['mice'], 'dislikes': ['cookies']}}]

In [50]:
sets = {1,2}

In [51]:
print (sets)

{1, 2}


In [52]:
def display(*arg1,**arg2):
    print(arg1)
    print(arg2)

In [53]:
display(12,13,name='deba',sal=1000)

(12, 13)
{'name': 'deba', 'sal': 1000}


In [59]:
mylist = [1,2,[3,4,5]]

In [55]:
import copy

In [61]:
list = copy.deepcopy(mylist)

In [62]:
list

[1, 2, [3, 4, 5]]

In [67]:
mylist
mylist[2]=9

In [64]:
mylist

[1, 2, 9]

In [65]:
list

[1, 2, [3, 4, 5]]

In [73]:
with open("abcs.txt","r") as fp:
    data = fp.readlines()
    for line in data: 
        print(line)

thi is deba 

this is deba2 


In [79]:
with open("abcs.txt","r+b") as fp:
    data = fp.read(5)
    print(data)
    pos= fp.tell()
    print(pos)
    fp.seek(0,2)
    pos=fp.tell()
    print(pos)
    

b'thi i'
5
27


In [5]:
from main import *
arithmatic.add(3,4)

NameError: name 'arithmatic' is not defined

In [6]:
import main

In [10]:
dir(main)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [11]:
import Main2

In [12]:
dir(Main2)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [13]:
import Main3

In [14]:
dir(Main3)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [15]:
from Main3 import addition

In [16]:
dir(Main3)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'addition']

In [20]:
class student:
    counter =0 
    def __init__(self,name):
        self.name=name
        student.counter +=1 
        
    
    
    
    def display(self):
        print(f"my name is {self.name}")
        print(f"registerred student is {student.counter}")
    
          

In [21]:
s1=student("debanjan")

In [22]:
s1.display()

my name is debanjan
registerred student is 1


In [23]:
s2=student("krishna")

In [24]:
s2.display()

my name is krishna
registerred student is 2


In [35]:
class A:
    def __init__(self,name):
        self.name=name
    def another(self):
        print("class A method ")
        
class B(A):
    def __init__(self,name,sal):
        super().__init__(name)
        self.sal=sal
        
    def display(self):
        self.another()
        print(f"my name is {self.name}")
        print(f"my sal is {self.sal}")
        

In [28]:
a=B("deban",123)

In [29]:
a.display()

class A method 
my name is deban
my sal is 123


In [30]:
import sqlite3

In [34]:
con = sqlite3.connect("mydb.db")

In [36]:
cur = con.cursor()

In [37]:
cur.execute("create table EMP(EMPID numb,NAME varchar, sal number)")

In [38]:
con.commit

<function Connection.commit>

In [43]:
cur.execute("insert into EMP(EMPID,NAME,sal) values(12,'debanjan',1234)")

OperationalError: database is locked

In [44]:
con.commit

<function Connection.commit>

In [51]:
import numpy as np
import sys
lst = range(1000)
print(sys.getsizeof(1))

narray=np.arrange(1000)
print(narray.itsemsize)


28


AttributeError: module 'numpy' has no attribute 'arrange'

In [56]:
import numpy as np 
a = np.array([(1,2,3,4),(5,6,7,8),(7,8,9,0)])
print(a)
print(a[2:0:-1, 2:0:-1])

[[1 2 3 4]
 [5 6 7 8]
 [7 8 9 0]]
[[9 8]
 [7 6]]


In [3]:
help (print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [4]:
a= 10

In [5]:
type(a)

int

In [6]:
a= "deba" 
type(a)

str

In [18]:
print ("hello","world",sep="==",end="\n")

hello==world


In [15]:
help (print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [26]:
a=10
b=30 
c=70
print ("values " , a , b,c )

values  10 30 70


In [30]:
print ("first value {0} second value {2} third value {0}".format(b,a,b))

first value 30 second value 30 third value 30


In [31]:
help(format)

Help on built-in function format in module builtins:

format(value, format_spec='', /)
    Return value.__format__(format_spec)
    
    format_spec defaults to the empty string.
    See the Format Specification Mini-Language section of help('FORMATTING') for
    details.



multiple variable 

okk

In [32]:
*dd

SyntaxError: can't use starred expression here (<ipython-input-32-dcdd29051c3f>, line 1)

*dd*

*dddddd

# okkk

In [36]:
c=13;d=14
print(c,d)
'''hello this is comment 
dfdfdfdf'''
d=c+d
print(d)

13 14
27


In [38]:
type (c) == int 

True

In [41]:
name = input ()

 debanjan


In [42]:
name

'debanjan'

In [44]:
"deba" + "deba"

'debadeba'

In [48]:
a=100
b=1000
if a>b:
    print("yes true")
else:
    print("out of if")

out of if


In [50]:
b = 10 
print (b)

10


In [52]:
b = 10 
while b > 0: 
    print (b)
    b= b -1
    if b ==4:
        break 

10
9
8
7
6
5


In [53]:
range (10)

range(0, 10)

In [56]:
list (range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [58]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [60]:
a=range(3,14,2)
list(a)

[3, 5, 7, 9, 11, 13]

In [62]:
help(isPrime)

NameError: name 'isPrime' is not defined

In [89]:
mystr = "this is my string"
mystr ="this is changed"

In [90]:
mystr;

In [91]:
mystr1 = "debanjan is good"
mystr1

'debanjan is good'

In [92]:
dir(mystr1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [94]:
help(mystr.__add__)

Help on method-wrapper object:

__add__ = class method-wrapper(object)
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __reduce__(...)
 |      Helper for pickle.
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __objclass__
 |  
 |  __self__
 |  
 |  __text_signature__



In [97]:
mystr1.__add__("very")

'debanjan is goodvery'

In [98]:
mystr1

'debanjan is good'

In [99]:
p = mystr1.__add__("very")

In [100]:
p

'debanjan is goodvery'

In [102]:
mystr1[2::]

'banjan is good'

In [114]:
mystr1[0:len(mystr1):1]

'debanjan is good'

In [116]:
len(mystr1)

16

In [122]:
mystr1[-1:len(mystr1):-1]

''

In [123]:
mystr1 = "this is the first tring"

In [127]:
mystr1[7:4:-1]

' si'

In [128]:
mylist = [1,2,3,'dd',3]
mylist

[1, 2, 3, 'dd', 3]

In [129]:
del mylist[0]

In [130]:
mylist

[2, 3, 'dd', 3]

In [137]:
mylist[2::-1]

['dd', 3, 2]

In [138]:
help(mylist)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [139]:
mylist

[2, 3, 'dd', 3]

In [144]:
mylist.sort()

TypeError: '<' not supported between instances of 'str' and 'int'

In [146]:
t = (1,2,3,5,6)

In [147]:
t

(1, 2, 3, 5, 6)

In [148]:
type (t)

tuple

In [1]:
mydict = {"deba":12 , "deba2":13}
mydict

{'deba': 12, 'deba2': 13}

In [2]:
mydict["deba"]

12

In [4]:
mydict.items()

dict_items([('deba', 12), ('deba2', 13)])

In [9]:
for key , val in mydict.items():
    print (key,val)


deba 12
deba2 13


In [1]:
dir(main)

NameError: name 'main' is not defined

In [3]:
import main

ModuleNotFoundError: No module named 'main'